name: Build-Branch

on:
  push:
    branches: [ testing-results ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go install

    - name: Install go-junit-results binary
      run: go install github.com/jstemmer/go-junit-report

    - name: Build
      run: go build -v -p 4

    - name: Test
      run: go test -v | go-junit-report > results.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: results.xml
